### PR TITLE
Fix latex image preamble

### PR DESCRIPTION
**Pull request by daverosoff**
I added some missing code to index.mbx (to tell the `mbx` script what preamble we need for the standalone images that get converted to pdf). I commented out some tabulars in two examples so that they would compile. They are now missing some text to the side and one of them is missing its color.

The color issue is because the LaTeX that was copied and pasted is using a color `M101_green` that is not a built-in color. We need the RGB color code for that color to make it work (probably in the original `.tex` source).

### CODE REVIEW

**Comment by daverosoff** [comment]
Lynda,

I rebased my work onto yours, so you should be able to merge with no conflicts if you want to.

**Comment by ladanielson** [comment]
Ok, I merged!  When I do a git status on my laptop I don't see any changes.  How do I pull those down?

**Comment by daverosoff** [comment]
Do git pull origin master. I'm not sure why it says you are up to date, but it's supposed to for some reason.

Sent from my metacoil
On Mon, Jul 11, 2016 at 6:45 PM, Lynda Danielson <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok, I merged! When I do a git status on my laptop I don't see any changes. How do I pull those down?

##

**Comment by daverosoff** [comment]
Sorry, I mean git pull origin generate-images

Sent from my metacoil
On Mon, Jul 11, 2016 at 6:55 PM, Dave Rosoff <drosoff@collegeofidaho.edu<mailto:drosoff@collegeofidaho.edu>> wrote:

Do git pull origin master. I'm not sure why it says you are up to date, but it's supposed to for some reason.

Sent from my metacoil
On Mon, Jul 11, 2016 at 6:45 PM, Lynda Danielson <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok, I merged! When I do a git status on my laptop I don't see any changes. How do I pull those down?

##

**Comment by ladanielson** [comment]
Done.  xslt still works, but I;m unable to generate images.  Were you able to get the mbx script to create svg images?

**Comment by daverosoff** [comment]
Yes, I cracked that as well.

Sent from my metacoil
On Mon, Jul 11, 2016 at 8:37 PM, Lynda Danielson <notifications@github.com<mailto:notifications@github.com>> wrote:

Done. xslt still works, but I;m unable to generate images. Were you able to get the mbx script to create svg images?

##

**Pull request merged**
