### PR TITLE
Conversionscript

### PR DESCRIPTION
**Pull request by davidfarmer**
The files in the LaTeXtoLaTeX directory are used to convert HTML to MBX.

Read the commands.txt file to see what to do.
(You need to do it from the command line.  It should be okay on a Mac or linux.  Not sure
about Windows.  We may need to ask someone for help.)

The index.mbx file has commented out some included files.  Uncomment them and run
xsltproc to see what errors need to be fixed in the html source.

Once those errors are fixed, we need to decide what to do with the tables.

We will probably have to go back-and-forth a few times to get everything working properly.

### CODE REVIEW

**Comment by ladanielson** [comment]
Hi David,
Thank you for all of your help!
Dave is over helping me with git now :)
I just pushed some more changes to preliminaries.xml which contains examples of converted tables (search for example add-the-opposite).  This format was recommended by Rob Beezer.

Should I wait to merge your pull request until you are able to incorporate more changes into your conversion script?

Thank you again!  Lynda

**Comment by davidfarmer** [comment]
Dear Lynda,

I suggest you merge my pull request, get on a new branch,
and then start fixing html errors.  You will need to uncomment
the files in index.mbx, run xslt, and then figure out which
mbx errors are caused by issues with the html source.  You can do that
in parallel with my work on the tables.

Regards,

David

**Comment by ladanielson** [comment]
Hi David,
I've managed to fix (or comment out) all the M101 html bugs.  I've run xslt on all the M101 sections and a "book" exists.  Dave Rosoff and I are working on the tikz code for the images now.  

Have you had any luck with a script to begin converting the html tables in the examples?  I was wondering if the tables would be easier to fix in the .mbx files now that they exist, or should this be done from the .html files?  Dave and I plan to investigate a fix for the tables tomorrow.

 I've pushed everything up to the new branch generate-images.

Thank you so much, Lynda

**Comment by davidfarmer** [comment]
Dear Lynda,

I was putting off the table conversion because I thought it was going to
be difficult, but I thought about it some more and it doesn't seem so bad.
It isn't quite working yet (the hard part is the last column, which is
a mixture of text and math), but I am getting close.

Regards,

David

**Pull request merged**
